version: '3'

networks:
    laravel-dev:

volumes:
    environment-data:

services:
    nginx:
        image: nginx:stable-alpine
        container_name: plans-head-nginx-server
        ports:
            - "8880:80"
        volumes:
            - ./src:/var/www/html
            - ./operations/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on: 
            - php
            - mysql
        networks:
            - laravel-dev
    mysql:
        image: mysql:5.7.22
        container_name: plans-head-mysql-server
        restart: unless-stopped
        tty: true
        ports:
            - "4306:3306"
        environment:
            MYSQL_DATABASE: plans-head
            MYSQL_USER: root
            MYSQL_PASSWORD: root123
            MYSQL_ROOT_PASSWORD: root123
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - laravel-dev
    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: plans-head-php
        volumes: 
            - ./src:/var/www/html
        ports:
            - "9000:9000"
        networks:
            - laravel-dev
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:4.9
        container_name: plans-head-phpmyadmin
        links:
            - mysql:mysql
        depends_on: 
            - mysql
        ports:
            - "8881:80"
        environment:
            - PMA_HOST=mysql
            - PMA_PORT=3306
        networks:
            - laravel-dev
    composer:
        image: composer:latest
        container_name: plans-head-composer
        volumes:
            - ./src:/var/www/html
        working_dir: /var/www/html
        networks:
            - laravel-dev
    npm:
        image: node:12.18
        container_name: plans-head-npm
        volumes: 
            - ./src:/var/www/html
        working_dir: /var/www/html
        entrypoint: ['npm']
        networks:
            - laravel-dev
    artisan:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: plans-head-artisan
        volumes:
            - ./src:/var/www/html
        depends_on:
            - mysql
        working_dir: /var/www/html
        entrypoint: ['/var/www/html/artisan']
        networks:
            - laravel-dev